version: "3.5"

services:
  postgres:
    container_name: myfinance-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-myfinance_db}
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres:/data/postgres
      
volumes:
  postgres: